### PR TITLE
feat: add ability to specify custom build output directory

### PR DESCRIPTION
**Pull request by jzxhuang**
Adds the ability to specify a custom build output directory. 

Notes:
* Thanks for your great work on this! Looking to make this change to make it usuable in a [Nx monorepo](https://nx.dev/) I work with, where the app is built to a path that looks like `dist/apps/...` (per Nx recommendations)
* Tests are passing, but didn't add any new tests — I think this would require creating a completely new fixture with a different `package.json`. If you'd like, I can add a new test suite
* Could probably pull `BUILD_OUTPUT_DIRECTORY` into a file named `utils.js` or something 🤷

### CODE REVIEW

**Comment by jzxhuang** [comment]
cc @jescalan thanks for creating this! Added a small PR here to support non-standard build directory. 

and if you're reading this, I also [opened an issue]("license": "GPL-2.0",) to add a `LICENSE` file to the repo root. Cheers 😄

**Comment by jescalan** [comment]
Hey sorry for the slow response here -- if you could add a test for this, that would be really wonderful 🙏

**Comment by jzxhuang** [comment]
@jescalan no worries, added a test! I had to rejig the `fixtures` setup to do so, making each "fixture" its own folder and updated the test script to iterate through them accordingly.

The new fixture `custom-output-directory` is a copy of the existing fixture, except that we output the next build to `/dist` in `next.config.js` and specify this accordingly in `nextBundleAnalysis` of `package.json`

**Comment by jescalan** [comment]
@jzxhuang this looks really great, thank you so much for this huge contribution!

@BRKalow would you be able to take a quick look at this, maybe run the tests locally and merge? I lost access since I don't work at hashicorp anymore 😭

**Comment by jzxhuang** [comment]
thanks @BRKalow! Would you also be able to:
* publish this version 
* Consider adding a LICENSE.md file (https://github.com/hashicorp/nextjs-bundle-analysis/issues/15)

ty 😇

**Comment by BRKalow** [comment]
Published, thanks for your patience! https://github.com/hashicorp/nextjs-bundle-analysis/releases/tag/0.4.0

**Pull request merged**
